### ISSUE TITLE
Build with valid signatures is needed for SimRel RC1

### ISSUE THREAD

**Issue by merks** [eclipse-dltk/dltk.core#2]
I just wanted to be sure that you're aware that DLTK's contribution to SimRel M3 is affected by this signing problem:

https://github.com/eclipse-simrel/simrel.build/issues/363

A new build is needed for RC1 tomorrow.

**Comment by zulus** [comment]
Should be fixed now: https://github.com/eclipse-simrel/simrel.build/pull/388

**Comment by merks** [comment]
Indeed it is fixed.  Thanks.  ❤️
